name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  native-image:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        java: [11]
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - name: Setup Windows C++ toolchain
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-latest' }}
      - name: sbt test plugin/scripted
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          export JABBA=/home/runner/bin/jabba
          $JABBA install graalvm@22.3.0
          export GRAALVM_HOME=$($JABBA which --home graalvm@22.3.0)
          $GRAALVM_HOME/bin/gu install native-image
          export NATIVE_IMAGE_COMMAND=$GRAALVM_HOME/bin/native-image
          sbt test plugin/scripted
      - name: sbt test
        shell: bash
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          sbt example/nativeImage
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - run: sbt checkAll
